### PR TITLE
Handle bad poll address

### PR DESCRIPTION
**Pull request by elliott-king**
Previously, an incorrect address would crash the site.

For example, if a correct address is `2537 18th st`, you can test against the incorrect inputs of `2537 18th` and `25 18th st`.

Probably not the most elegant solution. The express backend is sending a 200 response with a __json body__ that says the actual original error. I am less familiar with expressJS.

### CODE REVIEW

**Comment by bronzehedwick** [comment]
Thanks for contributing @elliott-king! This is definitely something we want to get addressed, so thanks again for finding the problem and working on a fix.

I checked out your code out, and get the following errors still when inputting the incorrect address:

```
XHRGEThttp://localhost:8000/api/v1/pollsite/2537%2018th/25%2018th%20st
[HTTP/1.1 500 Internal Server Error 19ms]

Uncaught (in promise) SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```

Is there something I'm missing in how to check this?

Thanks!

**Review by ktomanelli — APPROVED** [review]
Looks good to me, just tested and I'm not getting any errors. Tested working with '25 18th st', '2537 18th' and 'apple sauce', all of which crash the live site.

@bronzehedwick what address are you using to get the 500 error?

**Comment by bronzehedwick** [comment]
Hmm let me re-test then, maybe I did something strange locally.

**Comment by azlyth** [comment]
LGTM, I can see the "Address not found. Please try again." message. We can fix any further issues we find.

**Pull request merged**
