### PR TITLE
Add voting schedule box

### PR DESCRIPTION
**Pull request by bronzehedwick**
Use same style as tips info box, and align the box center.

### CODE REVIEW

**Comment by bronzehedwick** [comment]
This text appears in the copy document:

```
Early Voting Location
Normal Voting Location
```

But I wasn't sure what that meant or where to put it. If anyone has more insight into this I'd be grateful :)

**Comment by azlyth** [comment]
Looks like this is replicating the schedule that comes up when you do a search for an address. Is the idea to always show the schedule in a more prominent box?

Issue there is that it doesn't seem all early voting locations have the same hours. So even if the Astoria ones do, don't think we'd want people thinking that they're the same citywide.

**Comment by bronzehedwick** [comment]
Hmm good point. I think I just misinterpreted what needed to be accomplished here @azlyth. Maybe the updating copy ticket is already done, and we can decline this PR?

**Comment by azlyth** [comment]
Looks like this is indeed the schedule for all of NYC now. DIdn't seem to be the case for sure before, but now I see it here: https://www.vote.nyc/page/early-voting-information

In which case, this is probably the right way to display the early voting schedule. :+1:.

We should disable the schedule functionality in the map for now (but not remove the code, just toggle it off).

**Comment by bronzehedwick** [comment]
@azlyth Commented out the map schedule code.

**Pull request merged**
